const constants={
	ADD_USER : "ADD_USER",
	ADD_CURRENT_USER: "ADD_CURRENT_USER",
	VALIDATE_USER : "VALIDATE_USER",
	ADD_TASK : "ADD_TASK",
	DELETE_TASK : "DELETE_TASK",
	COMPLETE_TASK : "COMPLETE_TASK",
	UPDATE_NO_OF_TASKS : "UPDATE_NO_OF_TASKS",
	TOGGLE_LOGGEDIN : "TOGGLE_LOGGEDIN"
}

export default constants;